### PR TITLE
2.206 fix

### PR DESCRIPTION
**Pull request by Geming400**
I like never touched c++, so I made what I could, but I was able to build it.
The actions types `RemoveSelected` and `Removed` can't work as the `DeleteObject()` function is privated.

What I did:
- Updated the geode version and gd version to the correct ones
- *Disabled* the actions that can remove stuff
- updated `mod.json` to respect the new `mod.json` format
And that should be it

### CODE REVIEW

**Comment by Geming400** [comment]
Yeah so this won't likely be pulled
However, here's the mod's download link (for 2.206):
https://github.com/Geming400/WSLiveEditor/releases/tag/v2.1.5

**Comment by Geming400** [comment]
@iAndyHD3 2.206 fix is here
Changelog: https://github.com/Geming400/WSLiveEditor/releases/tag/v2.2.0

**Review by Geming400 — COMMENTED** [review]
This now will likely get pulled, at-least I hope

**Comment by Thepuppetqueen57** [comment]
someone pull this PLEASE

**Comment by Geming400** [comment]
@Thepuppetqueen57 my code is way too messy to be pulled, I can try fixing that in the future.
If you already didn't you can download my changes: https://github.com/Geming400/WSLiveEditor/releases/tag/v2.1.5

**Comment by Geming400** [comment]
I tried fixing some things, but I don't think I've fixed everything. At least I hope I did

**Pull request closed without merging**
